name: flutter_application_1
description: "A new Flutter project to open camera button."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.0.0
  camera: ^0.10.5+4
  path_provider: ^2.0.10
  pdf: ^3.6.0     # Add this for PDF generation
  share: ^2.0.4   # Add this for sharing functionality
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  